// <auto-generated />
namespace W2022A6AZB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addedpropertytoholdrichtextartistalbum : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedpropertytoholdrichtextartistalbum));
        
        string IMigrationMetadata.Id
        {
            get { return "202204130549431_added-property-to-hold-rich-text-artist-album"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
