// <auto-generated />
namespace W2022A6AZB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class increaserichTextpropertylength : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(increaserichTextpropertylength));
        
        string IMigrationMetadata.Id
        {
            get { return "202204132008089_increase-richText-property-length"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
